name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # You can adjust this version if needed

    - name: Install dependencies
      run: npm install

    - name: Build the Vue project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # This is automatically provided by GitHub Actions
        publish_dir: ./dist  # This is the folder where the built Vue project is located

    - name: Clean up old GitHub Pages branches
      run: |
        git fetch --all
        git branch -D gh-pages || true
        git push origin --delete gh-pages || true
