name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # Adjust as necessary

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build  # Build your React app for production

    - name: Disable Jekyll
      run: echo "" > build/.nojekyll  # Prevent Jekyll from interfering with your build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Deploy the contents of the build folder
