name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch

permissions:
  contents: write  # This grants the GitHub Actions bot write access to the repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Adjust Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Build the Vue project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
